import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Check,ChevronRight,Disc3,Flame,Headphones,Heart,ListMusic,Mic2,Music2,Plus,Save,Search,Shuffle,Sparkles,Trash2,X}from'lucide-react';
import'./styles.css';

const seedSongs=[
{id:'mot-nha',title:'Một Nhà',artist:'Da LAB',genre:'Nhạc trẻ',year:'2019',mood:'Vui',rarity:'SỬ THI',color:'#bd6c2d',lyrics:'Khi hai ta về một nhà khép đôi mi chung một giường',plays:'18.2K'},
{id:'noi-nay-co-anh',title:'Nơi Này Có Anh',artist:'Sơn Tùng M-TP',genre:'Pop',year:'2017',mood:'Lãng mạn',rarity:'HUYỀN THOẠI',color:'#7454c8',lyrics:'Em là ai từ đâu bước đến nơi đây dịu dàng chân phương',plays:'24.1K'},
{id:'co-chang-trai',title:'Có Chàng Trai Viết Lên Cây',artist:'Phan Mạnh Quỳnh',genre:'Ballad',year:'2019',mood:'Sâu lắng',rarity:'SỬ THI',color:'#5b7853',lyrics:'Có chàng trai viết lên cây lời yêu thương cô gái ấy',plays:'16.7K'},
{id:'thang-tu',title:'Tháng Tư Là Lời Nói Dối Của Em',artist:'Hà Anh Tuấn',genre:'Ballad',year:'2016',mood:'Sâu lắng',rarity:'HIẾM',color:'#3c7390',lyrics:'Mùa xuân có em như chưa bắt đầu và cơn gió khẽ mơn man',plays:'13.9K'},
{id:'di-tron',title:'Đưa Nhau Đi Trốn',artist:'Đen ft. Linh Cáo',genre:'Rap',year:'2015',mood:'Chill',rarity:'HIẾM',color:'#7b6847',lyrics:'Bố em hút rất nhiều thuốc mẹ em khóc mắt lệ nhòa',plays:'11.4K'},
{id:'ngay-dau-tien',title:'Ngày Đầu Tiên',artist:'Đức Phúc',genre:'Pop',year:'2022',mood:'Lãng mạn',rarity:'SỬ THI',color:'#9f5570',lyrics:'Ngày đầu tiên cùng nhau sống suốt đời cùng nhìn về một phía',plays:'19.6K'},
{id:'sau-tat-ca',title:'Sau Tất Cả',artist:'Erik',genre:'Ballad',year:'2016',mood:'Tâm trạng',rarity:'HUYỀN THOẠI',color:'#42607c',lyrics:'Sau tất cả mình lại trở về với nhau tựa như chưa bắt đầu',plays:'27.3K'},
{id:'vi-me',title:'Vì Mẹ Anh Bắt Chia Tay',artist:'Miu Lê ft. Karik',genre:'Nhạc trẻ',year:'2022',mood:'Vui',rarity:'HIẾM',color:'#9c4c39',lyrics:'Anh rất tốt thế nhưng thà rằng em không gặp anh',plays:'14.8K'},
{id:'mua-co-don',title:'Bước Qua Mùa Cô Đơn',artist:'Vũ.',genre:'Indie',year:'2020',mood:'Chill',rarity:'HIẾM',color:'#4a6b72',lyrics:'Chào cơn mưa làm sao cứ kéo ta quay lại',plays:'12.5K'},
{id:'em-gai-mua',title:'Em Gái Mưa',artist:'Hương Tràm',genre:'Ballad',year:'2017',mood:'Tâm trạng',rarity:'SỬ THI',color:'#4d69a1',lyrics:'Mưa trôi cả bầu trời nắng trượt theo những nỗi buồn',plays:'22.8K'}];
const norm=v=>v.toLocaleLowerCase('vi').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');
function Logo(){return <div className="logo"><span><Mic2/><Flame/></span><div><strong>KÉT NHẠC</strong><small>HUYỀN ÂM</small></div></div>}
function SongCard({song,queued,liked,onAdd,onLike}){return <article className="song-card" style={{'--tone':song.color}}><div className="song-art"><Disc3/><span>{song.rarity}</span><button onClick={()=>onLike(song.id)} aria-label={`Yêu thích ${song.title}`} className={liked?'liked':''}><Heart fill={liked?'currentColor':'none'}/></button></div><div className="song-body"><small>{song.genre} · {song.year}</small><h3>{song.title}</h3><p>{song.artist}</p><div><span>{song.mood}</span><span>{song.plays} lượt hát</span></div></div><button className={`queue-add ${queued?'added':''}`} onClick={()=>onAdd(song)} disabled={queued}>{queued?<><Check/> ĐÃ TRONG DANH SÁCH</>:<><Plus/> THÊM BÀI</>}</button></article>}
function App(){
const[songs,setSongs]=useState(()=>{try{return JSON.parse(localStorage.getItem('ketnhac-custom')||'[]').concat(seedSongs)}catch{return seedSongs}});
const[queue,setQueue]=useState(()=>{try{return JSON.parse(localStorage.getItem('ketnhac-queue')||'[]')}catch{return[]}});const[likes,setLikes]=useState(()=>{try{return JSON.parse(localStorage.getItem('ketnhac-likes')||'[]')}catch{return[]}});const[query,setQuery]=useState('');const[genre,setGenre]=useState('Tất cả');const[opening,setOpening]=useState(false);const[reveal,setReveal]=useState(null);const[toast,setToast]=useState('');const[drawer,setDrawer]=useState(false);const[addOpen,setAddOpen]=useState(false);const[form,setForm]=useState({title:'',artist:'',lyrics:'',genre:'Nhạc trẻ'});
useEffect(()=>localStorage.setItem('ketnhac-likes',JSON.stringify(likes)),[likes]);
const notify=t=>{setToast(t);clearTimeout(window.__kt);window.__kt=setTimeout(()=>setToast(''),2200)};const add=s=>{if(!queue.some(x=>x.id===s.id)){setQueue(q=>[...q,s]);notify(`Đã thêm “${s.title}”`)}};const remove=id=>setQueue(q=>q.filter(s=>s.id!==id));const saveQueue=()=>{localStorage.setItem('ketnhac-queue',JSON.stringify(queue));notify(`Đã lưu ${queue.length} bài trên thiết bị`)};
const openChest=()=>{if(opening)return;setReveal(null);setOpening(true);setTimeout(()=>{const pool=songs.filter(s=>!queue.some(q=>q.id===s.id));setReveal((pool.length?pool:songs)[Math.floor(Math.random()*(pool.length?pool.length:songs.length))]);setOpening(false)},1400)};
const filtered=useMemo(()=>{const q=norm(query);return songs.filter(s=>(genre==='Tất cả'||s.genre===genre)&&(!q||norm(`${s.title} ${s.artist} ${s.lyrics}`).includes(q)))},[songs,query,genre]);const recs=useMemo(()=>{const prefs=[...queue.map(x=>x.genre),...songs.filter(x=>likes.includes(x.id)).map(x=>x.genre)];return songs.filter(x=>!queue.some(q=>q.id===x.id)).sort((a,b)=>prefs.filter(g=>g===b.genre).length-prefs.filter(g=>g===a.genre).length).slice(0,4)},[queue,likes,songs]);
const submit=e=>{e.preventDefault();if(!form.title.trim()||!form.artist.trim())return;const item={...form,id:`custom-${Date.now()}`,year:'Của bạn',mood:'Tự chọn',rarity:'MỚI',color:'#3d7f87',plays:'0'};setSongs(s=>[item,...s]);localStorage.setItem('ketnhac-custom',JSON.stringify([item,...songs.filter(x=>x.id.startsWith('custom-'))]));setForm({title:'',artist:'',lyrics:'',genre:'Nhạc trẻ'});setAddOpen(false);notify('Đã thêm bài hát mới')};
return <div className="app"><header className="top"><Logo/><nav><a href="#kho">Kho nhạc</a><a href="#de-cu">Đề cử</a></nav><button className="ghost" onClick={()=>setAddOpen(true)}><Plus/> Thêm nhạc</button><button className="queue-pill" onClick={()=>setDrawer(true)}><ListMusic/><b>{queue.length}</b><span>Danh sách hát</span></button></header><main><section className="hero"><div className="hero-copy"><span className="overline"><Sparkles/> KHO BÁU ÂM NHẠC</span><h1>Mở két.<br/><em>Gặp đúng bài.</em></h1><p>Không cần tranh nhau chọn nhạc. Để vận may gọi tên ca khúc tiếp theo của cả nhóm.</p><div className="hero-actions"><button className="primary" onClick={openChest}><Shuffle/>{opening?'ĐANG KHAI MỞ...':'KHAI MỞ KÉT NHẠC'}</button><button className="secondary" onClick={()=>document.querySelector('#kho').scrollIntoView({behavior:'smooth'})}>TỰ CHỌN BÀI <ChevronRight/></button></div><div className="trust"><span><b>128</b> ca khúc</span><i/><span><b>{queue.length}</b> bài đang chờ</span><i/><span>Lưu ngay trên máy</span></div></div><div className={`chest-scene ${opening?'opening':''} ${reveal?'revealed':''}`}><div className="rune r1">✦</div><div className="rune r2">✧</div><div className="rune r3">✦</div><div className="chest-glow"/><img src="/magic-music-chest.png" alt="Rương nhạc ma thuật"/><div className="loot-card">{reveal&&<><small>KÉT ĐÃ CHỌN</small><strong>{reveal.title}</strong><span>{reveal.artist}</span><button onClick={()=>add(reveal)}><Plus/> THÊM VÀO DANH SÁCH</button></>}</div></div></section>
<section className="workspace" id="kho"><div className="section-title"><div><span className="overline">HÁT GÌ TIẾP ĐÂY?</span><h2>Kho bài hát</h2></div><button className="outline" onClick={()=>setAddOpen(true)}><Plus/> Thêm bài của bạn</button></div><div className="searchbar"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm tên bài, ca sĩ hoặc nhập một câu trong lời bài hát..."/><kbd>Tìm cả lời bài hát</kbd></div><div className="genres">{['Tất cả','Nhạc trẻ','Pop','Ballad','Rap','Indie'].map(g=><button key={g} onClick={()=>setGenre(g)} className={genre===g?'active':''}>{g}</button>)}</div><div className="results-note">{query?<><b>{filtered.length}</b> kết quả cho “{query}” — đã tìm trong tên, ca sĩ và lời bài hát.</>:<>Gợi ý nổi bật cho đêm nay</>}</div><div className="song-grid">{filtered.map(s=><SongCard key={s.id} song={s} queued={queue.some(q=>q.id===s.id)} liked={likes.includes(s.id)} onAdd={add} onLike={id=>setLikes(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}/>)}</div>{!filtered.length&&<div className="empty"><Music2/><h3>Chưa tìm thấy bài phù hợp</h3><p>Thử một câu khác trong lời bài hát hoặc thêm bài mới vào kho.</p><button onClick={()=>setAddOpen(true)}>Thêm bài hát</button></div>}</section>
<section className="recommend" id="de-cu"><div className="section-title"><div><span className="overline">DỰA TRÊN GU CỦA BẠN</span><h2>Danh sách đề cử</h2></div><span className="rec-note"><Sparkles/> Tự cập nhật theo bài đã thêm và yêu thích</span></div><div className="rec-list">{recs.map((s,i)=><article key={s.id}><b>{String(i+1).padStart(2,'0')}</b><div className="rec-disc" style={{'--tone':s.color}}><Disc3/></div><div><h3>{s.title}</h3><p>{s.artist} · {s.genre}</p></div><span>{s.mood}</span><button onClick={()=>add(s)}><Plus/> Thêm</button></article>)}</div></section></main>
<aside className={`drawer ${drawer?'open':''}`}><div className="drawer-head"><div><span className="overline">ĐÊM KARAOKE</span><h2>Danh sách hát <b>{queue.length}</b></h2></div><button onClick={()=>setDrawer(false)}><X/></button></div>{queue.length?<><div className="queue-list">{queue.map((s,i)=><article key={s.id}><b>{String(i+1).padStart(2,'0')}</b><span className="queue-art" style={{'--tone':s.color}}><Music2/></span><div><strong>{s.title}</strong><small>{s.artist}</small></div><button onClick={()=>remove(s.id)} aria-label={`Bỏ ${s.title}`}><Trash2/></button></article>)}</div><div className="drawer-foot"><button className="save" onClick={saveQueue}><Save/> LƯU DANH SÁCH</button><p>Danh sách được lưu riêng trên thiết bị này.</p></div></>:<div className="drawer-empty"><Headphones/><h3>Danh sách đang trống</h3><p>Thêm vài bài rồi mở két để tìm ca khúc bất ngờ tiếp theo.</p></div>}</aside>{drawer&&<button className="scrim" onClick={()=>setDrawer(false)} aria-label="Đóng danh sách"/>}
{addOpen&&<div className="modal"><form onSubmit={submit}><div className="modal-head"><div><span className="overline">BỔ SUNG KHO NHẠC</span><h2>Thêm bài hát</h2></div><button type="button" onClick={()=>setAddOpen(false)}><X/></button></div><label>Tên bài hát<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ví dụ: Bài hát của chúng ta" autoFocus/></label><label>Ca sĩ<input value={form.artist} onChange={e=>setForm({...form,artist:e.target.value})} placeholder="Tên ca sĩ"/></label><label>Thể loại<select value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})}><option>Nhạc trẻ</option><option>Pop</option><option>Ballad</option><option>Rap</option><option>Indie</option><option>Khác</option></select></label><label>Một đoạn lời bài hát<textarea value={form.lyrics} onChange={e=>setForm({...form,lyrics:e.target.value})} placeholder="Giúp tìm lại bài hát bằng lời..."/></label><button className="primary submit"><Plus/> THÊM VÀO KHO</button></form></div>}{toast&&<div className="toast"><Check/>{toast}</div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
