import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import { createPortal } from 'react-dom';
import { History } from 'lucide-react';
import { HISTORY_KEY, readSpinHistory, appendSpinHistory } from './spinHistory';
import{Check,ChevronRight,Disc3,ExternalLink,Flame,Headphones,Heart,ListMusic,LoaderCircle,LogIn,LogOut,Mic2,Music2,Plus,Radio,Save,Search,Shuffle,Sparkles,Trash2,UserRound,X}from'lucide-react';
import'./styles.css';
import { supabase } from './supabase';
import { sortByPlays } from './songPopularity';
import { artworkFor } from './songArtwork';
import { usePlaylists } from './usePlaylists';
import { PlaylistManager } from './PlaylistManager';
import { appendUniqueSongs } from './playlists';

const seedSongs=[
{id:'mot-nha',title:'Một Nhà',artist:'Da LAB',genre:'Nhạc trẻ',year:'2019',mood:'Vui',rarity:'SỬ THI',difficulty:'Dễ',color:'#3fc67a',lyrics:'Khi hai ta về một nhà khép đôi mi chung một giường',plays:'18.2K'},
{id:'noi-nay-co-anh',title:'Nơi Này Có Anh',artist:'Sơn Tùng M-TP',genre:'Pop',year:'2017',mood:'Lãng mạn',rarity:'HUYỀN THOẠI',difficulty:'Vừa',color:'#39a8e8',lyrics:'Em là ai từ đâu bước đến nơi đây dịu dàng chân phương',plays:'24.1K'},
{id:'co-chang-trai',title:'Có Chàng Trai Viết Lên Cây',artist:'Phan Mạnh Quỳnh',genre:'Ballad',year:'2019',mood:'Sâu lắng',rarity:'SỬ THI',difficulty:'Khó',color:'#9667ed',lyrics:'Có chàng trai viết lên cây lời yêu thương cô gái ấy',plays:'16.7K'},
{id:'thang-tu',title:'Tháng Tư Là Lời Nói Dối Của Em',artist:'Hà Anh Tuấn',genre:'Ballad',year:'2016',mood:'Sâu lắng',rarity:'HIẾM',difficulty:'Khó',color:'#9667ed',lyrics:'Mùa xuân có em như chưa bắt đầu và cơn gió khẽ mơn man',plays:'13.9K'},
{id:'di-tron',title:'Đưa Nhau Đi Trốn',artist:'Đen ft. Linh Cáo',genre:'Rap',year:'2015',mood:'Chill',rarity:'HIẾM',difficulty:'Dễ',color:'#3fc67a',lyrics:'Bố em hút rất nhiều thuốc mẹ em khóc mắt lệ nhòa',plays:'11.4K'},
{id:'ngay-dau-tien',title:'Ngày Đầu Tiên',artist:'Đức Phúc',genre:'Pop',year:'2022',mood:'Lãng mạn',rarity:'SỬ THI',difficulty:'Vừa',color:'#39a8e8',lyrics:'Ngày đầu tiên cùng nhau sống suốt đời cùng nhìn về một phía',plays:'19.6K'},
{id:'sau-tat-ca',title:'Sau Tất Cả',artist:'Erik',genre:'Ballad',year:'2016',mood:'Tâm trạng',rarity:'HUYỀN THOẠI',difficulty:'Thử thách',color:'#ef4b55',lyrics:'Sau tất cả mình lại trở về với nhau tựa như chưa bắt đầu',plays:'27.3K'},
{id:'vi-me',title:'Vì Mẹ Anh Bắt Chia Tay',artist:'Miu Lê ft. Karik',genre:'Nhạc trẻ',year:'2022',mood:'Vui',rarity:'HIẾM',difficulty:'Vừa',color:'#39a8e8',lyrics:'Anh rất tốt thế nhưng thà rằng em không gặp anh',plays:'14.8K'},
{id:'mua-co-don',title:'Bước Qua Mùa Cô Đơn',artist:'Vũ.',genre:'Indie',year:'2020',mood:'Chill',rarity:'HIẾM',difficulty:'Dễ',color:'#3fc67a',lyrics:'Chào cơn mưa làm sao cứ kéo ta quay lại',plays:'12.5K'},
{id:'em-gai-mua',title:'Em Gái Mưa',artist:'Hương Tràm',genre:'Ballad',year:'2017',mood:'Tâm trạng',rarity:'SỬ THI',difficulty:'Thử thách',color:'#ef4b55',lyrics:'Mưa trôi cả bầu trời nắng trượt theo những nỗi buồn',plays:'22.8K'}];
const norm=v=>v.toLocaleLowerCase('vi').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');
const tier={Dễ:'easy',Vừa:'medium',Khó:'hard','Thử thách':'expert'};
const difficultyForGenre=g=>/classical|opera|metal/i.test(g)?'Thử thách':/rock|hip-hop|rap/i.test(g)?'Khó':/dance|electronic|r&b|soul/i.test(g)?'Vừa':'Dễ';
function Logo(){return <div className="logo"><span><Mic2/><Flame/></span><div><strong>singkangsong</strong><small>KARAOKE RANDOM</small></div></div>}
function SongCard({song,queued,liked,onAdd,onLike}){const artwork=artworkFor(song);const[failedArtwork,setFailedArtwork]=useState(null);return <article className={`song-card tier-${tier[song.difficulty]||'easy'}`} style={{'--tone':song.color}}><div className={`song-art ${artwork&&failedArtwork!==artwork?'has-artwork':''}`}><Disc3/>{artwork&&failedArtwork!==artwork&&<img className="song-cover" src={artwork} alt={`Ảnh bìa ${song.title} · ${song.artist}${song.id==='di-tron'?' (Chill Version)':''}`} loading="lazy" decoding="async" referrerPolicy="no-referrer" onError={()=>setFailedArtwork(artwork)}/>}<span>{song.source==='online'?'TRỰC TUYẾN':song.rarity}</span><b>{song.difficulty}</b><button onClick={()=>onLike(song.id)} aria-label={`Lưu ${song.title} vào danh sách`} className={liked?'liked':''}><ListMusic/></button></div><div className="song-body"><small>{song.genre} · {song.year}</small><h3>{song.title}</h3><p>{song.artist}</p><div><span className="difficulty-dot">{song.difficulty}</span>{song.source==='online'&&song.url?<a href={song.url} target="_blank" rel="noreferrer">Apple Music <ExternalLink/></a>:<span>{song.plays} lượt hát</span>}</div></div><button className={`queue-add ${queued?'added':''}`} onClick={()=>onAdd(song)} disabled={queued}>{queued?<><Check/> ĐÃ TRONG DANH SÁCH</>:<><Plus/> THÊM BÀI</>}</button></article>}
function VinylResult({song,onClose,onRemove,onNext}){
 const artwork=artworkFor(song);const[failed,setFailed]=useState(null);
 const[mobile,setMobile]=useState(()=>window.matchMedia('(max-width:760px)').matches);const closeButton=useRef(null);
 useEffect(()=>{const media=window.matchMedia('(max-width:760px)');const update=()=>setMobile(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
 useEffect(()=>{if(!mobile)return;const before=document.body.style.overflow;const previous=document.activeElement;document.body.style.overflow='hidden';closeButton.current?.focus();const escape=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const buttons=closeButton.current?.parentElement.querySelectorAll('button');if(!buttons?.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',escape);return()=>{document.body.style.overflow=before;document.removeEventListener('keydown',escape);previous?.focus()}},[mobile,onClose]);
 const content=<div className="vinyl-result" role="region" aria-label="Bài hát được chọn" aria-live="polite" style={{'--record-tone':song.color||'#39a8e8'}}>
  <button ref={closeButton} className="vinyl-close" onClick={onClose} aria-label="Đóng kết quả để mở rương lại"><X/></button>
  <div className="vinyl-record" aria-label={`Đĩa nhạc ${song.title}`}><div className="vinyl-label">{artwork&&failed!==artwork?<img src={artwork} alt={`Ảnh bìa ${song.title}`} onError={()=>setFailed(artwork)}/>:<Disc3/>}<i className="vinyl-spindle"/></div></div>
  <div className="vinyl-caption"><small>KÉT ĐÃ CHỌN · {song.difficulty}</small><strong>{song.title}</strong><span>{song.artist}</span></div>
  <div className="vinyl-actions"><button onClick={onRemove}><Trash2/> BỎ BÀI NÀY</button><button onClick={onNext}><Shuffle/> BỐC BÀI KHÁC</button></div>
 </div>;
 return mobile?createPortal(<div className="mobile-result-overlay" role="dialog" aria-modal="true" aria-label={'Kết quả quay: '+song.title}><button className="mobile-result-backdrop" onClick={onClose} aria-label="Đóng kết quả" tabIndex={-1}/>{content}</div>,document.body):content;
}
function App(){
const[history,setHistory]=useState(()=>readSpinHistory(localStorage));const[historyOpen,setHistoryOpen]=useState(false);
useEffect(()=>{try{localStorage.setItem(HISTORY_KEY,JSON.stringify(history))}catch{/* History stays available for this session if storage is full. */}},[history]);
const[songs,setSongs]=useState(()=>{try{return JSON.parse(localStorage.getItem('ketnhac-custom')||'[]').map(x=>({...x,difficulty:x.difficulty||'Vừa',color:x.color||'#39a8e8'})).concat(seedSongs)}catch{return seedSongs}});
const[queue,setQueue]=useState(()=>{try{return JSON.parse(localStorage.getItem('ketnhac-queue')||'[]').map(x=>seedSongs.find(s=>s.id===x.id)||({...x,difficulty:x.difficulty||'Vừa',color:x.color||'#39a8e8'}))}catch{return[]}});const[user,setUser]=useState(null);const[pendingSong,setPendingSong]=useState(null);const[authBusy,setAuthBusy]=useState(false);const[authMessage,setAuthMessage]=useState('');const[authMode,setAuthMode]=useState('login');const[query,setQuery]=useState('');const[genre,setGenre]=useState('Tất cả');const[level,setLevel]=useState('Tất cả');const[onlineSongs,setOnlineSongs]=useState([]);const[onlineStatus,setOnlineStatus]=useState('idle');const[opening,setOpening]=useState(false);const[reveal,setReveal]=useState(null);const[chestTier,setChestTier]=useState('medium');const[toast,setToast]=useState('');const[drawer,setDrawer]=useState(false);const[addOpen,setAddOpen]=useState(false);const[accountOpen,setAccountOpen]=useState(false);const[loginForm,setLoginForm]=useState({name:'',email:'',password:''});const[form,setForm]=useState({title:'',artist:'',lyrics:'',genre:'Nhạc trẻ',difficulty:'Vừa'});
useEffect(()=>{
 if(!supabase)return;
 let active=true;
 const apply=u=>{if(active)setUser(u?{id:u.id,email:u.email,name:u.user_metadata?.name||u.email.split('@')[0]}:null)};
 supabase.auth.getSession().then(({data,error})=>{if(error&&active)setAuthMessage(error.message);apply(data.session?.user)});
 const {data}=supabase.auth.onAuthStateChange((_event,session)=>apply(session?.user));
 return()=>{active=false;data.subscription.unsubscribe()};
},[]);
useEffect(()=>{const term=query.trim();if(term.length<2){setOnlineSongs([]);setOnlineStatus('idle');return}const controller=new AbortController();setOnlineStatus('loading');const timer=setTimeout(async()=>{try{const response=await fetch(`${import.meta.env.BASE_URL}api/search?q=${encodeURIComponent(term)}`,{signal:controller.signal});if(!response.ok)throw new Error(`Search failed: ${response.status}`);const data=await response.json();const mapped=(data.results||[]).filter(x=>x.trackName&&x.artistName).map(x=>{const difficulty=difficultyForGenre(x.primaryGenreName||'Pop');return{id:`itunes-${x.trackId}`,title:x.trackName,artist:x.artistName,genre:x.primaryGenreName||'Pop',year:(x.releaseDate||'').slice(0,4)||'Mới',mood:'Danh mục mới',rarity:'ONLINE',difficulty,color:{Dễ:'#3fc67a',Vừa:'#39a8e8',Khó:'#9667ed','Thử thách':'#ef4b55'}[difficulty],lyrics:'',plays:'Mới',source:'online',artwork:(x.artworkUrl100||x.artworkUrl60||'').replace(/\/\d+x\d+bb\./,'/600x600bb.'),url:x.trackViewUrl}});setOnlineSongs(mapped);setOnlineStatus('done')}catch(error){if(error.name!=='AbortError'){setOnlineSongs([]);setOnlineStatus('error')}}},450);return()=>{clearTimeout(timer);controller.abort()}},[query]);
const notify=t=>{setToast(t);clearTimeout(window.__kt);window.__kt=setTimeout(()=>setToast(''),2200)};const add=s=>{if(!queue.some(x=>x.id===s.id)){setQueue(q=>[...q,s]);notify(`Đã thêm “${s.title}”`)}};const remove=id=>setQueue(q=>q.filter(s=>s.id!==id));const saveQueue=()=>{localStorage.setItem('ketnhac-queue',JSON.stringify(queue));notify(`Đã lưu ${queue.length} bài trên thiết bị`)};
const library=usePlaylists(user?.id,notify);
const savedSongs=library.playlists.flatMap(p=>p.songs);
const savedIds=new Set(savedSongs.map(s=>s.id));
const saveToPlaylist=id=>{const song=[...songs,...onlineSongs,...savedSongs].find(s=>s.id===id);if(!song)return;setPendingSong(song);setAccountOpen(true)};
const addAllSongs=items=>{const additions=appendUniqueSongs(queue,items).length-queue.length;setQueue(current=>appendUniqueSongs(current,items));notify(additions?'Đã thêm '+additions+' bài vào danh sách hát':'Tất cả bài đã có trong danh sách hát')};
const login=async e=>{
 e.preventDefault();if(!supabase){setAuthMessage('Chưa cấu hình kết nối Supabase.');return}
 setAuthBusy(true);setAuthMessage('');
 try{
 const email=loginForm.email.trim();
 const {data,error}=authMode==='signup'?await supabase.auth.signUp({email,password:loginForm.password,options:{data:{name:loginForm.name.trim()},emailRedirectTo:window.location.origin+import.meta.env.BASE_URL}}):await supabase.auth.signInWithPassword({email,password:loginForm.password});
 if(error)throw error;
 if(authMode==='signup'&&!data.session)setAuthMessage('Kiểm tra email xác nhận tài khoản trước khi đăng nhập.');
 else{setAccountOpen(false);setLoginForm({name:'',email:'',password:''});notify('Đã đăng nhập')}
 }catch(error){setAuthMessage(error.message)}finally{setAuthBusy(false)}
};
const logout=async()=>{const {error}=await supabase.auth.signOut();if(error){setAuthMessage(error.message);return}setAccountOpen(false);notify('Đã đăng xuất')};
const openChest=()=>{if(opening)return;if(!queue.length){setDrawer(true);notify('Hãy chọn ít nhất một bài trước khi mở két');return}const pick=queue[Math.floor(Math.random()*queue.length)];setReveal(null);setChestTier(tier[pick.difficulty]||'easy');setOpening(true);setTimeout(()=>{setReveal(pick);setHistory(items=>appendSpinHistory(items,pick));setOpening(false)},1550)};
const closeReveal=()=>setReveal(null);const removeReveal=()=>{if(!reveal)return;const picked=reveal;setQueue(q=>q.filter(s=>s.id!==picked.id));setReveal(null);notify(`Đã bỏ “${picked.title}” để không bị chọn lại`)};
const filtered=useMemo(()=>{const q=norm(query);const local=songs.filter(s=>(genre==='Tất cả'||s.genre===genre)&&(level==='Tất cả'||s.difficulty===level)&&(!q||norm(`${s.title} ${s.artist} ${s.lyrics}`).includes(q)));const remote=onlineSongs.filter(s=>(genre==='Tất cả'||s.genre===genre)&&(level==='Tất cả'||s.difficulty===level));return sortByPlays([...local,...remote.filter(r=>!local.some(l=>norm(`${l.title}${l.artist}`)===norm(`${r.title}${r.artist}`)))])},[songs,onlineSongs,query,genre,level]);const recs=useMemo(()=>{const prefs=[...queue.map(x=>x.genre),...songs.filter(x=>savedIds.has(x.id)).map(x=>x.genre)];return songs.filter(x=>!queue.some(q=>q.id===x.id)).sort((a,b)=>prefs.filter(g=>g===b.genre).length-prefs.filter(g=>g===a.genre).length).slice(0,4)},[queue,library.playlists,songs]);
const submit=e=>{e.preventDefault();if(!form.title.trim()||!form.artist.trim())return;const colors={Dễ:'#3fc67a',Vừa:'#39a8e8',Khó:'#9667ed','Thử thách':'#ef4b55'};const item={...form,id:`custom-${Date.now()}`,year:'Của bạn',mood:'Tự chọn',rarity:'MỚI',color:colors[form.difficulty],plays:'0'};setSongs(s=>[item,...s]);localStorage.setItem('ketnhac-custom',JSON.stringify([item,...songs.filter(x=>x.id.startsWith('custom-'))]));setForm({title:'',artist:'',lyrics:'',genre:'Nhạc trẻ',difficulty:'Vừa'});setAddOpen(false);notify('Đã thêm bài hát mới')};
return <div className="app"><header className="top"><Logo/><nav><a href="#kho">Kho nhạc</a><a href="#de-cu">Đề cử</a></nav><button className="ghost" onClick={()=>setAddOpen(true)}><Plus/> Thêm nhạc</button><button className="account-pill" onClick={()=>setAccountOpen(true)}><UserRound/><span>{user?user.name:'Đăng nhập'}</span></button><button className="history-button" onClick={()=>setHistoryOpen(true)} aria-label="Lịch sử đã quay"><History/><span>Lịch sử</span></button><button className="queue-pill" onClick={()=>setDrawer(true)}><ListMusic/><b>{queue.length}</b><span>Danh sách hát</span></button></header><main><section className="hero"><div className="hero-copy"><span className="overline"><Sparkles/> BỐC TRONG DANH SÁCH ĐÃ CHỌN</span><h1>Mở két.<br/><em>Gặp đúng bài.</em></h1><p>Thêm những bài cả nhóm muốn hát, rồi để chiếc két chọn ngẫu nhiên bài tiếp theo.</p><div className="hero-actions"><button className="primary" onClick={openChest}><Shuffle/>{opening?'ĐANG KHAI MỞ...':'KHAI MỞ KÉT NHẠC'}</button><button className="secondary" onClick={()=>document.querySelector('#kho').scrollIntoView({behavior:'smooth'})}>CHỌN THÊM BÀI <ChevronRight/></button></div><div className="trust"><span><Radio/><b>Kho trực tuyến</b></span><i/><span><b>{queue.length}</b> bài đã chọn</span><i/><span>Đỏ là khó nhất</span></div></div><div className={`chest-scene tier-${chestTier} ${opening?'opening':''} ${reveal?'revealed':''}`}><div className="rune r1">✦</div><div className="rune r2">✧</div><div className="rune r3">✦</div><div className="energy-ring er1"/><div className="energy-ring er2"/><div className="beam b1"/><div className="beam b2"/><div className="chest-glow"/><div className="chest-figure" aria-label="Rương nhạc ma thuật"><div className="chest-open-light"/><img className="chest-image" src={`${import.meta.env.BASE_URL}magic-music-chest.png`} alt="Rương nhạc ma thuật"/></div>{reveal&&<VinylResult key={reveal.id} song={reveal} onClose={closeReveal} onRemove={removeReveal} onNext={openChest}/>}</div></section>
<section className="workspace" id="kho"><div className="section-title"><div><span className="overline">KHO NHẠC KHỔNG LỒ · CẬP NHẬT TRỰC TUYẾN</span><h2>Tìm bài muốn hát</h2></div><button className="outline" onClick={()=>setAddOpen(true)}><Plus/> Thêm bài của bạn</button></div><div className="searchbar"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nhập tên bài hoặc ca sĩ để tìm trong kho nhạc trực tuyến..."/>{onlineStatus==='loading'?<span className="live-state loading"><LoaderCircle/> Đang tìm</span>:<span className="live-state"><Radio/> Trực tuyến</span>}</div><div className="filter-row"><div className="genres">{['Tất cả','Nhạc trẻ','Pop','Ballad','Rap','Indie'].map(g=><button key={g} onClick={()=>setGenre(g)} className={genre===g?'active':''}>{g}</button>)}</div><div className="levels">{['Tất cả','Dễ','Vừa','Khó','Thử thách'].map(x=><button key={x} onClick={()=>setLevel(x)} className={`${level===x?'active ':''}${x==='Tất cả'?'all':tier[x]||''}`}>{x}</button>)}</div></div><div className="difficulty-legend"><span className="easy">Dễ</span><span className="medium">Vừa</span><span className="hard">Khó</span><span className="expert">Thử thách</span><em>Màu sắc biểu thị độ khó khi hát</em></div><p className="results-note">Sắp xếp theo lượt hát giảm dần · lượt hát trong kho mẫu là dữ liệu mẫu; bài chưa có số liệu nằm cuối.</p><div className="results-note">{query?<><b>{filtered.length}</b> kết quả cho “{query}” {onlineStatus==='loading'?'· đang mở rộng tìm kiếm trực tuyến…':onlineStatus==='error'?'· kho trực tuyến tạm gián đoạn':'· gồm kho cá nhân và danh mục trực tuyến hiện hành'}.</>:<>Bài nổi bật trong kho cá nhân · nhập từ khóa để mở rộng ra kho trực tuyến</>}</div><div className="song-grid">{filtered.map(s=><SongCard key={s.id} song={s} queued={queue.some(q=>q.id===s.id)} liked={savedIds.has(s.id)} onAdd={add} onLike={saveToPlaylist}/>)}</div>{!filtered.length&&onlineStatus!=='loading'&&<div className="empty"><Music2/><h3>Chưa tìm thấy bài phù hợp</h3><p>Thử tên ca sĩ, một từ khóa khác hoặc thêm bài mới vào kho.</p><button onClick={()=>setAddOpen(true)}>Thêm bài hát</button></div>}</section>
<section className="recommend" id="de-cu"><div className="section-title"><div><span className="overline">DỰA TRÊN GU CỦA BẠN</span><h2>Danh sách đề cử</h2></div><span className="rec-note"><Sparkles/> Tự cập nhật theo bài đã thêm và danh sách nhạc</span></div><div className="rec-list">{recs.map((s,i)=><article key={s.id}><b>{String(i+1).padStart(2,'0')}</b><div className="rec-disc" style={{'--tone':s.color}}><Disc3/></div><div><h3>{s.title}</h3><p>{s.artist} · {s.genre}</p></div><span>{s.mood}</span><button onClick={()=>add(s)}><Plus/> Thêm</button></article>)}</div></section></main>
<aside className={`drawer ${drawer?'open':''}`}><div className="drawer-head"><div><span className="overline">ĐÊM KARAOKE</span><h2>Danh sách hát <b>{queue.length}</b></h2></div><button onClick={()=>setDrawer(false)}><X/></button></div>{queue.length?<><div className="queue-list">{queue.map((s,i)=><article key={s.id}><b>{String(i+1).padStart(2,'0')}</b><span className="queue-art" style={{'--tone':s.color}}><Music2/></span><div><strong>{s.title}</strong><small>{s.artist}</small></div><button onClick={()=>remove(s.id)} aria-label={`Bỏ ${s.title}`}><Trash2/></button></article>)}</div><div className="drawer-foot"><button className="save" onClick={saveQueue}><Save/> LƯU DANH SÁCH</button><p>Danh sách được lưu riêng trên thiết bị này.</p></div></>:<div className="drawer-empty"><Headphones/><h3>Danh sách đang trống</h3><p>Thêm vài bài rồi mở két để tìm ca khúc bất ngờ tiếp theo.</p></div>}</aside>{drawer&&<button className="scrim" onClick={()=>setDrawer(false)} aria-label="Đóng danh sách"/>}
{addOpen&&<div className="modal"><form onSubmit={submit}><div className="modal-head"><div><span className="overline">BỔ SUNG KHO NHẠC</span><h2>Thêm bài hát</h2></div><button type="button" onClick={()=>setAddOpen(false)}><X/></button></div><label>Tên bài hát<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ví dụ: Bài hát của chúng ta" autoFocus/></label><label>Ca sĩ<input value={form.artist} onChange={e=>setForm({...form,artist:e.target.value})} placeholder="Tên ca sĩ"/></label><div className="form-grid"><label>Thể loại<select value={form.genre} onChange={e=>setForm({...form,genre:e.target.value})}><option>Nhạc trẻ</option><option>Pop</option><option>Ballad</option><option>Rap</option><option>Indie</option><option>Khác</option></select></label><label>Độ khó<select value={form.difficulty} onChange={e=>setForm({...form,difficulty:e.target.value})}><option>Dễ</option><option>Vừa</option><option>Khó</option><option>Thử thách</option></select></label></div><label>Một đoạn lời bài hát<textarea value={form.lyrics} onChange={e=>setForm({...form,lyrics:e.target.value})} placeholder="Giúp tìm lại bài hát bằng lời..."/></label><button className="primary submit"><Plus/> THÊM VÀO KHO</button></form></div>}
{historyOpen&&<div className="modal history-modal" role="dialog" aria-modal="true" aria-label="Lịch sử đã quay"><div className="account-card"><div className="modal-head"><h2>Lịch sử đã quay</h2><button onClick={()=>setHistoryOpen(false)} aria-label="Đóng lịch sử"><X/></button></div><p className="account-note">Lưu tối đa 200 lượt quay gần nhất trên thiết bị này.</p><div className="spin-history">{history.map(item=><article key={item.id}><div><strong>{item.song.title}</strong><span>{item.song.artist}</span><time dateTime={new Date(item.at).toISOString()}>{new Date(item.at).toLocaleString('vi-VN')}</time></div><button disabled={queue.some(s=>s.id===item.song.id)} onClick={()=>add(item.song)}><Plus/> {queue.some(s=>s.id===item.song.id)?'Đã có':'Thêm vào hát'}</button></article>)}</div>{!history.length&&<p className="account-note">Chưa có lượt quay nào. Mở rương để bắt đầu!</p>}</div></div>}{accountOpen&&<div className="modal account-modal" role="dialog" aria-modal="true" aria-label="Tài khoản">{user?<div className="account-card"><div className="modal-head"><h2>{user.name}</h2><button onClick={()=>setAccountOpen(false)} aria-label="Đóng hồ sơ"><X/></button></div><p className="account-note">{user.email}</p><PlaylistManager library={library} onAdd={add} onAddAll={addAllSongs} pendingSong={pendingSong} onCancelSong={()=>setPendingSong(null)}/><button className="secondary logout-button" onClick={logout}><LogOut/> ĐĂNG XUẤT</button></div>:<form onSubmit={login}><div className="modal-head"><h2>{authMode==='signup'?'Tạo tài khoản':'Đăng nhập'}</h2><button type="button" onClick={()=>setAccountOpen(false)} aria-label="Đóng đăng nhập"><X/></button></div><p className="account-note">Đăng nhập để lưu danh sách nhạc và đồng bộ giữa các thiết bị.</p>{authMode==='signup'&&<label>Tên hiển thị<input required value={loginForm.name} onChange={e=>setLoginForm({...loginForm,name:e.target.value})}/></label>}<label>Email<input required type="email" autoComplete="email" value={loginForm.email} onChange={e=>setLoginForm({...loginForm,email:e.target.value})}/></label><label>Mật khẩu<input required type="password" minLength={6} autoComplete={authMode==='signup'?'new-password':'current-password'} value={loginForm.password} onChange={e=>setLoginForm({...loginForm,password:e.target.value})}/></label>{authMessage&&<p className="account-note" role="status">{authMessage}</p>}<button className="primary submit" disabled={authBusy}><LogIn/>{authBusy?'ĐANG XỬ LÝ…':authMode==='signup'?'TẠO TÀI KHOẢN':'ĐĂNG NHẬP'}</button><button className="auth-switch" type="button" onClick={()=>{setAuthMode(v=>v==='signup'?'login':'signup');setAuthMessage('')}}>{authMode==='signup'?'Đã có tài khoản? Đăng nhập':'Chưa có tài khoản? Đăng ký'}</button></form>}</div>}{toast&&<div className="toast"><Check/>{toast}</div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
